basic working example
wesleytodd/react-express-middleware pull request #5
Opened 2016-11-29 15:46 UTC by amberleyromo

resolves #4 with beginning simple example

2016-11-29 16:24 UTC, wesleytodd requested changes
Overall looks good.  I will run it now just to test.

2016-11-29 16:24 UTC, wesleytodd commented on example/handlers/adieu/index.jsx
> +	var RenderComponent = (<PageWrapper>
A more legible format for this:

```javascript
var RenderComponent = (
  <PageWrapper>
    <Container name="Lorelai" />
  </PageWrapper>
);
```

See how it lines the starting and ending parts up so they are easily identifiable?  This helps others read your code.

2016-11-29 16:24 UTC, wesleytodd commented on example/handlers/howdy/container.jsx
> +				<p>Howdy. It{"'"}s a {this.props.adjective} day.</p>
Are you sure this, `{"'"}`, is required?

2016-11-29 16:24 UTC, wesleytodd commented on example/browser.js
> +require('es6-promise').polyfill();
In examples I try to slim things down to their minimum possible requirements.  And it doesn't look like you are using promises anywhere?  Also, this was for browser support, which we might be able to remove even in our apps, so we can remove them in the examples for sure.

2016-11-29 16:59 UTC, amberleyromo commented on example/browser.js
> +require('es6-promise').polyfill();
removed

2016-11-29 16:59 UTC, amberleyromo commented on example/handlers/howdy/container.jsx
> +				<p>Howdy. It{"'"}s a {this.props.adjective} day.</p>
nope. removed.

2016-11-29 16:59 UTC, amberleyromo commented on example/handlers/adieu/index.jsx
> +	var RenderComponent = (<PageWrapper>
modified.

2016-12-06 17:07 UTC, wesleytodd requested changes

2016-12-06 17:07 UTC, wesleytodd commented on README.md
> +Run the ([working example](example/)) by running `npm run example` from the root.
drop the parens, it reads better as just "run the working example by"

2016-12-06 17:07 UTC, wesleytodd commented on example/components/page-wrapper.jsx
> +					<h1>Header from {'<PageWrapper>'}</h1>
This still reads weird to me, can we just change it to `Header from PageWrapper` to avoid the complexity?

2016-12-06 17:07 UTC, wesleytodd commented on package.json
> +    "example": "npm run babel && cd ./example && npm run-script start"
you can just do `npm start` as a short hand, fyi.

2016-12-06 17:59 UTC, amberleyromo reviewed
naming/style changes made

2016-12-06 20:50 UTC, wesleytodd commented on example/components/header.jsx
> +					<h1>Header from {'<Header>'}</h1>
Sorry, maybe I wasn't clear on the change I hoped for here.  I just want to drop the angle brackets so we don't need the weird curly/quote thing:  `<h1>Header from Header</h1>`

2016-12-07 20:51 UTC, closed without merging